config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :uniquevenues

  root "uniquevenues#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uniquevenue.rb
class Uniquevenue < ApplicationRecord
  validates :uniquevenue_name, presence: true, length: { in: 1..30, messages: "1~30文字の範囲で入力してください" }
  validates :uniquevenue_description, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :adress, presence: true, uniqueness: true
  validates :holding_space, presence: true, uniqueness: true
  validates :inquiry, presence: true
  validates :access, presence: true
end

app/models/uniquevenue_image.rb
class UniquevenueImage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uniquevenues_controller.rb
class UniquevenuesController < ApplicationController

  def index
   @uniquevenues = Uniquevenue.all
  end

  def show
    @uniquevenue = Uniquevenue.find(params[:id])
  end

  def new
    @uniquevenue = Uniquevenue.new
  end

  def create
    #render plain: params[:house].inspect
    @uniquevenue = Uniquevenue.new(uniquevenue_params)
    if @uniquevenue.save
      redirect_to uniquevenues_path
    else
     render 'new'
    end
  end

  def edit
    @uniquevenue = Uniquevenue.find(params[:id])
  end

  def update
    @uniquevenue = Uniquevenue.find(params[:id])
    if @uniquevenue.update(uniquevenue_params)
      redirect_to uniquevenues_path
    else
      render 'edit'
    end
  end

  def destroy
    @uniquevenue = Uniquevenue.find(params[:id])
    @uniquevenue.destroy
    redirect_to uniquevenues_path
  end


  private
    def uniquevenue_params
      params.require(:uniquevenue).permit(:uniquevenue_name, :uniquevenue_description, :price, :adress, :parking, :inquiry, :holding_space, :access)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uniquevenues_helper.rb
module UniquevenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniqueVenue</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/uniquevenues/_form.html.erb
<%= form_for @uniquevenue do |f| %>

<p>
  <%= f.text_field :uniquevenue_name, placeholder: "enter uniquevenue_name" %>
  <% if @uniquevenue.errors.messages[:uniquevenue_name].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:uniquevenue][0] %></span>
  <% end %>
</p>

<p>
  <%= f.text_area :uniquevenue_description, placeholder: "enter uniquevenue_description" %>
  <% if @uniquevenue.errors.messages[:uniquevenue_description].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:uniquevenue_description][0] %></span>
  <% end %>
</p>

<p>
  <%= f.number_field :price, placeholder: "enter price" %>
  <% if @uniquevenue.errors.messages[:price].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:price][0] %></span>
  <% end %>
</p>

<p>
  <%= f.text_field :adress, placeholder: "enter adress" %>
  <% if @uniquevenue.errors.messages[:adress].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:adress][0] %></span>
  <% end %>
</p>

<p>
  <%= f.text_field :parking, placeholder: "enter parking" %>
  <% if @uniquevenue.errors.messages[:parking].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:parking][0] %></span>
  <% end %>
</p>

<p>
  <%= f.text_area :inquiry, placeholder: "enter inquiry" %>
  <% if @uniquevenue.errors.messages[:inquiry].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:inquiry][0] %></span>
  <% end %>
</p>

<p>
  <%= f.text_field :holding_space, placeholder: "enter holding_space" %>
  <% if @uniquevenue.errors.messages[:holding_space].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:holding_space][0] %></span>
  <% end %>
</p>

<p>
  <%= f.text_field :access, placeholder: "enter access" %>
  <% if @uniquevenue.errors.messages[:access].any? %>
  <span class="error"><%= @uniquevenue.errors.messages[:access][0] %></span>
  <% end %>
</p>

<%= f.submit %>

<% end %>

app/views/uniquevenues/edit.html.erb
<h2>編集</h2>
<%= render 'form' %>

app/views/uniquevenues/index.html.erb
<h2>
  ユニークベニュー一覧
  <%= link_to "ユニークベニューの登録", new_uniquevenue_path, class: "header-menu" %>
</h2>
<ul>
  <% @uniquevenues.each do |uniquevenue| %>
  <li>
    <%= link_to uniquevenue.uniquevenue_name, uniquevenue_path(uniquevenue) %>
    <%= link_to "編集", edit_uniquevenue_path(uniquevenue), class: "command" %>
    <%= link_to "削除", uniquevenue_path(uniquevenue), method: :delete, class: "command", data: { confirm: '削除しますか？' } %>
  </li>
  <% end %>
</ul>

app/views/uniquevenues/new.html.erb
<h2>登録</h2>
<%= render 'form' %>

app/views/uniquevenues/show.html.erb
<h2><%= @uniquevenue.uniquevenue_name %></h2>

<p><%= @uniquevenue.uniquevenue_name %></p>

<p><%= @uniquevenue.uniquevenue_description %></p>

<p><%= @uniquevenue.price %></p>

<p><%= @uniquevenue.adress %></p>


<%= link_to "Back", root_path %>